name: Build Chromebook Drivers Free Edition
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup MSBuild System
      uses: microsoft/setup-msbuild@v2

    - name: Compile Free Mux Driver (crosectypec)
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:TargetType=Driver /p:DriverType=WDM crosectypec.vcxproj

    - name: Compile Free IOM Driver (inteltcss)
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:TargetType=Driver /p:DriverType=WDM inteltcss.vcxproj
        
    - name: Upload Both Finished Free Binaries
      uses: actions/upload-artifact@v4
      with:
        name: Clean-Free-Chromebook-Drivers
        path: |
          **/crosectypec.sys
          **/inteltcss.sys
